# Generated by Django 2.2 on 2020-03-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbconf',
            old_name='host',
            new_name='address',
        ),
        migrations.AlterUniqueTogether(
            name='dbconf',
            unique_together={('name', 'address', 'env', 'port')},
        ),
    ]
