# Generated by Django 2.2 on 2020-04-01 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sqlmng', '0002_auto_20200331_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='InceptionSql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('committer', models.CharField(max_length=20)),
                ('sql_content', models.TextField(blank=True, null=True)),
                ('env', models.IntegerField(choices=[(1, '生产环境'), (2, '测试环境')])),
                ('db_name', models.CharField(max_length=50)),
                ('treater', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(-2, '已回滚'), (-1, '待执行'), (0, '执行成功'), (1, '已放弃'), (2, '执行失败')], default=-1)),
                ('execute_info', models.TextField(blank=True, default='', null=True)),
                ('exe_affected_rows', models.CharField(max_length=10)),
                ('roll_affected_rows', models.CharField(max_length=10)),
                ('rollback_id', models.TextField(blank=True, null=True)),
                ('rollback_db', models.CharField(max_length=100)),
                ('sql_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
