# Generated by Django 2.2 on 2020-04-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0003_inceptionsql'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inceptionsql',
            options={},
        ),
        migrations.AlterModelTable(
            name='inceptionsql',
            table='inceptionsql',
        ),
    ]
