# Generated by Django 2.2 on 2020-04-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0004_auto_20200401_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbconf',
            name='env',
            field=models.IntegerField(blank=True, choices=[(1, '生产'), (2, '测试')], null=True),
        ),
    ]
