# Generated by Django 2.2 on 2020-04-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0006_remove_inceptionsql_execute_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionsql',
            name='execute_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
