# Generated by Django 2.2 on 2020-04-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0007_inceptionsql_execute_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inceptionsql',
            options={'ordering': ['-id']},
        ),
    ]
