# Generated by Django 2.2 on 2020-02-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('address', models.CharField(max_length=256, verbose_name='地址')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('number', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='编号')),
                ('size', models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='U型')),
                ('idc', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cmdb.Idc', verbose_name='所属机房')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('name', 'idc')},
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('uuid', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='UUID')),
                ('cpu', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='磁盘大小')),
                ('ip', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='ip地址')),
                ('business', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='业务线')),
                ('server_type', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='服务器类型')),
                ('daq', models.TextField(blank=True, default='', null=True, verbose_name='数据采集')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '在线')], default=1, verbose_name='运行状态')),
                ('rack', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cmdb.Rack', verbose_name='所属机柜')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('uuid', 'server_type')},
            },
        ),
    ]
