# Generated by Django 2.2 on 2020-04-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200329_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': '用户表', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='user',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', '总监'), ('2', '经理'), ('3', '研发')], default='3', max_length=32),
        ),
    ]
