# Generated by Django 2.2 on 2020-04-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_group'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
    ]
