# Generated by Django 2.2 on 2020-04-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200416_2236'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='groups',
        ),
    ]
