# Generated by Django 2.2 on 2020-04-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200418_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
